# Generated by Django 6.0.6 on 2026-08-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
