# Generated by Django 6.0.6 on 2026-08-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_rating', models.IntegerField()),
                ('communication_rating', models.IntegerField()),
                ('problem_solving_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('recommendation', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
        ),
    ]
