# Generated by Django 6.0.6 on 2026-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_interviewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
    ]
